graphql:
  playground:
    enabled: true

spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true
  datasource:
    url: jdbc:postgres://tai.db.elephantsql.com/pjqsyaji
    username: pjqsyaji
    password: csjYy1hrcepMwldClxBc7BGT_cQTrPbe
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode:
      schema-locations: classpath:/schema.sql
      continue-on-error: true