graphql:
  playground:
    enabled: true

spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: pjqsyaji
    password: csjYy1hrcepMwldClxBc7BGT_cQTrPbe
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://tai.db.elephantsql.com/pjqsyaji
